# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_description', models.CharField(max_length=600)),
                ('event_location', models.CharField(max_length=200)),
                ('event_start', models.DateTimeField(verbose_name='event start')),
                ('event_end', models.DateTimeField(verbose_name='event end')),
                ('event_duration_min', models.IntegerField(default=0)),
                ('event_cost', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
