# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-12 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160910_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubevent',
            options={'ordering': ['-event_date']},
        ),
        migrations.AddField(
            model_name='clubevent',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='event_cost',
            field=models.IntegerField(default=0, verbose_name='event_cost'),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='event_date',
            field=models.DateTimeField(verbose_name='event_date'),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='event_description',
            field=models.CharField(help_text='Add description Box i.e: This workshop will be about...', max_length=600, verbose_name='event_description'),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='event_duration_min',
            field=models.IntegerField(default=0, verbose_name='event_duration_min'),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='event_location',
            field=models.CharField(max_length=200, verbose_name='event_location'),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='event_title',
            field=models.CharField(max_length=200, verbose_name='event_title'),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='votes'),
        ),
    ]
